# Generated by Django 4.1.5 on 2023-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_order_wallet_wallethistory_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='current_wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='previous_wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
