# Generated by Django 4.1.5 on 2023-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_wallethistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
