# Generated by Django 4.1.5 on 2023-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_wallethistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
