# Generated by Django 4.1.5 on 2023-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_rename_products_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
