# Generated by Django 4.1.5 on 2023-01-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_wallet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='ecommerce_app.product'),
        ),
    ]
